# Generated by Django 4.2.1 on 2023-06-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='time',
        ),
        migrations.AddField(
            model_name='shipment',
            name='date_delivered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
